//! Rec.2020 colourspace transformation matrices
//!
//! **Auto-generated - do not edit directly!**
//! Generated by tools/src/bin/generate_constants.rs
//!
//! ITU-R BT.2020 (Rec.2020) is a wide colour gamut standard for UHDTV.
//! These matrices use monochromatic primaries (630nm, 532nm, 467nm) with D65 white point.

/// VSF RGB → Rec.2020 transformation matrix
///
/// Converts linear VSF RGB (703nm, 523nm, 462nm primaries, Illuminant E white)
/// to linear Rec.2020 RGB (630nm, 532nm, 467nm primaries, D65 white point).
///
/// Matrix layout (column-major):
/// - Indices 0-2: Red channel contributions from [red, green, blue]
/// - Indices 3-5: Green channel contributions from [red, green, blue]
/// - Indices 6-8: Blue channel contributions from [red, green, blue]
pub const VSF_RGB2REC2020: [f32; 9] = [
    1.205768486407741f32, -0.06575040007922661f32, 0.0017731225420240682f32,
    -0.12042948538841566f32, 1.0619582570188875f32, 0.027606096823561105f32,
    0.02257381250101076f32, -0.030623026243884757f32, 0.8877658000180177f32,
];

/// Rec.2020 → VSF RGB transformation matrix
///
/// Converts linear Rec.2020 RGB to linear VSF RGB.
/// Inverse of VSF_RGB2REC2020.
pub const REC2020_2VSF_RGB: [f32; 9] = [
    0.834559216684474f32, 0.051576833136512075f32, -0.0032706946011182977f32,
    0.09510806561955171f32, 0.9466907720876403f32, -0.029628394527889793f32,
    -0.01794018928035957f32, 0.03134413445223846f32, 1.1254843573870534f32,
];
