//! Rec.2020 colourspace transformation matrices
//!
//! **Auto-generated - do not edit directly!** Generated by tools/src/bin/generate_constants.rs
//!
//! ITU-R BT.2020 (Rec.2020) is a wide colour gamut standard for UHDTV. These matrices use its monochromatic primaries (630nm, 532nm, 467nm), evaluated under the Stockman & Sharpe 2000 10° cone fundamentals, with the D65 white (CIE 2019 spectral power distribution under the same fundamentals) adapted to Illuminant E by von Kries scaling in LMS. CIE 1931 is not involved. Rec.2020 [1,1,1] ↔ VSF RGB [1,1,1].

/// VSF RGB → Rec.2020 transformation matrix
///
/// Converts linear VSF RGB (703nm, 523nm, 462nm primaries, Illuminant E white) to linear Rec.2020 RGB (630nm, 532nm, 467nm primaries, D65 white point).
///
/// Matrix layout (column-major):
/// - Indices 0-2: Red channel contributions from [red, green, blue]
/// - Indices 3-5: Green channel contributions from [red, green, blue]
/// - Indices 6-8: Blue channel contributions from [red, green, blue]
pub const VSF_RGB2REC2020: [f32; 9] = [
    1.190_846_4_f32,
    -0.053_325_053_f32,
    0.000_355_520_98_f32,
    -0.237_984_39_f32,
    1.152_500_6_f32,
    0.011_038_954_f32,
    0.047_137_987_f32,
    -0.099_175_57_f32,
    0.988_605_5_f32,
];

/// Rec.2020 → VSF RGB transformation matrix
///
/// Converts linear Rec.2020 RGB to linear VSF RGB. Inverse of VSF_RGB2REC2020.
pub const REC2020_2VSF_RGB: [f32; 9] = [
    0.847_592_83_f32,
    0.039_153_423_f32,
    -0.000_742_004_66_f32,
    0.175_241_5_f32,
    0.874_940_6_f32,
    -0.009_832_771_f32,
    -0.022_834_33_f32,
    0.085_905_98_f32,
    1.010_574_8_f32,
];

#[cfg(feature = "spirix")]
pub use s44_consts::*;

#[cfg(feature = "spirix")]
mod s44_consts {
    use spirix::{sf, ScalarF4E4 as S44};

    pub const VSF_RGB2REC2020_S44: [S44; 9] = [
        sf!(1.190_846_4_f32),
        sf!(-0.053_325_053_f32),
        sf!(0.000_355_520_98_f32),
        sf!(-0.237_984_39_f32),
        sf!(1.152_500_6_f32),
        sf!(0.011_038_954_f32),
        sf!(0.047_137_987_f32),
        sf!(-0.099_175_57_f32),
        sf!(0.988_605_5_f32),
    ];

    pub const REC2020_2VSF_RGB_S44: [S44; 9] = [
        sf!(0.847_592_83_f32),
        sf!(0.039_153_423_f32),
        sf!(-0.000_742_004_66_f32),
        sf!(0.175_241_5_f32),
        sf!(0.874_940_6_f32),
        sf!(-0.009_832_771_f32),
        sf!(-0.022_834_33_f32),
        sf!(0.085_905_98_f32),
        sf!(1.010_574_8_f32),
    ];
}
