//! CIE XYZ colourimetric transformation matrices
//!
//! **Auto-generated - do not edit directly!**
//! Generated by tools/src/bin/generate_constants.rs
//!
//! XYZ is a device-independent colourimetric standard, not a spectral colour space.
//! These matrices convert between VSF RGB (spectrally-defined primaries) and
//! CIE 1931 XYZ colour space.

/// VSF RGB → XYZ transformation matrix
///
/// Converts linear VSF RGB (703nm, 523nm, 462nm primaries) to CIE 1931 XYZ colour space.
/// Derived from CIE 1931 2° Standard Observer colour matching functions with white point
/// scaling so that RGB=[1,1,1] maps to Illuminant E (equal energy spectrum).
///
/// Matrix layout (row-major):
/// - Row 0: Red primary [x, y, z]
/// - Row 1: Green primary [x, y, z]
/// - Row 2: Blue primary [x, y, z]
pub const VSF_RGB2XYZ: [f32; 9] = [
    0.7569807839833361, 0.27161306261822465, 0,
    0.08271896297783411, 0.6901602365625348, 0.059632489120823244,
    0.16030025303882994, 0.038226700819240816, 0.940367510879177,
];

/// XYZ → VSF RGB transformation matrix
///
/// Converts CIE 1931 XYZ colour space to linear VSF RGB.
/// Inverse of VSF_RGB2XYZ.
pub const XYZ2VSF_RGB: [f32; 9] = [
    1.3730104305431237, -0.5422538573820304, 0.03438649982795189,
    -0.14484764374212294, 1.5112518747155992, -0.09583456460926235,
    -0.22816278680100083, 0.031001982666430936, 1.0614480647813105,
];
